[package]
edition = "2018"
name = "rusty-gql"
version = "0.1.0"

[workspace]
members = ["examples/*", "codegen"]

[dependencies]
anyhow = "1.0.44"
askama = "0.10.5"
async-trait = "0.1.51"
axum = "0.2.5"
futures = "0.3.17"
graphql-parser = "0.3.0"
rusty-gql-codegen = {path = "codegen"}
serde = "1.0.130"
