[package]
edition = "2018"
name = "rusty-gql"
version = "0.1.0"

[workspace]
members = ["examples/*", "derive"]

[dependencies]
anyhow = "1.0.44"
askama = "0.10.5"
async-trait = "0.1.51"
axum = "0.2.5"
graphql-parser = "0.3.0"
rusty-gql-derive = {path = "derive"}
serde = "1.0.130"
