[package]
edition = "2021"
name = "rusty-gql-axum-example"
version = "0.1.1"

[dependencies]
axum = {version = "0.4.2", features = ["headers"]}
hyper = "0.14.16"
rusty-gql = {path = "../.."}
rusty-gql-axum = {path = "../../frameworks/axum"}
tokio = {version = "1.12.0", features = ["full"]}
