[package]
name = "rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
rusty-gql = { path = "../..", version = "0.1.0" }
serde_json = "1.0.72"

[toolchain]
channel = "nightly"
