[package]
name = "rusty-gql-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
axum = { version = "0.4.2", features = ["ws", "headers"] }
rusty-gql = { path = "../..", version = "0.1.0" }
serde_urlencoded = "0.7.0"
