name: Book

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'

jobs:
  deploy:
    name: Deploy book on GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
      - run: mdbook build docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
