name: Book

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'

jobs:
  deploy:
    name: Deploy book on GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
      - name: Render book
        run: |
          mdbook build -d gh-pages/master docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keepFiles: true
          publish_dir: docs/book/gh-pages
